namespace KLC.Enums;

/// <summary>
/// Represents the status of an e-invoice.
/// </summary>
public enum EInvoiceStatus
{
    /// <summary>
    /// E-invoice is pending generation.
    /// </summary>
    Pending = 0,

    /// <summary>
    /// E-invoice is being generated by the provider.
    /// </summary>
    Processing = 1,

    /// <summary>
    /// E-invoice was successfully generated and signed.
    /// </summary>
    Issued = 2,

    /// <summary>
    /// E-invoice generation failed.
    /// </summary>
    Failed = 3,

    /// <summary>
    /// E-invoice was cancelled.
    /// </summary>
    Cancelled = 4
}
