using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Uow;
using KLC.Authorization;
using KLC.ChargingSessions;
using KLC.Ocpp.Events;

namespace KLC.Ocpp.Handlers;

/// <summary>
/// Handles StartTransaction messages from charge points.
/// Creates a new charging session and validates the RFID tag.
/// </summary>
public class StartTransactionHandler : IOcppMessageHandler
{
    private readonly IChargingSessionRepository _sessionRepository;
    private readonly IIdTagRepository _idTagRepository;
    private readonly IDistributedEventBus _eventBus;
    private readonly IUnitOfWorkManager _uowManager;
    private readonly ILogger<StartTransactionHandler> _logger;
    private readonly IGuidGenerator _guidGenerator;

    public StartTransactionHandler(
        IChargingSessionRepository sessionRepository,
        IIdTagRepository idTagRepository,
        IDistributedEventBus eventBus,
        IUnitOfWorkManager uowManager,
        ILogger<StartTransactionHandler> logger,
        IGuidGenerator guidGenerator)
    {
        _sessionRepository = sessionRepository;
        _idTagRepository = idTagRepository;
        _eventBus = eventBus;
        _uowManager = uowManager;
        _logger = logger;
        _guidGenerator = guidGenerator;
    }

    public async Task<JObject> HandleAsync(
        string chargePointId,
        JObject payload,
        CancellationToken cancellationToken)
    {
        try
        {
            // Extract payload fields
            var connectorId = payload.Value<int>("connectorId");
            var idTag = payload.Value<string>("idTag");
            var meterStart = payload.Value<int>("meterStart");
            var timestampStr = payload.Value<string>("timestamp");
            var reservationId = payload.Value<int?>("reservationId");

            if (string.IsNullOrWhiteSpace(idTag))
            {
                _logger.LogWarning(
                    "StartTransaction missing idTag for charge point {ChargePointId}, connector {ConnectorId}",
                    chargePointId, connectorId);
                return BuildErrorResponse(0, "Invalid");
            }

            var timestamp = DateTime.TryParse(timestampStr, out var parsed)
                ? parsed
                : DateTime.UtcNow;

            // Validate idTag
            var tag = await _idTagRepository.FindByTagIdAsync(idTag, cancellationToken: cancellationToken);
            var tagStatus = ValidateTag(tag);

            if (tagStatus != "Accepted")
            {
                _logger.LogWarning(
                    "StartTransaction rejected: tag {IdTag} status {TagStatus} on {ChargePointId}, connector {ConnectorId}",
                    idTag, tagStatus, chargePointId, connectorId);
                return BuildErrorResponse(0, tagStatus);
            }

            using var uow = _uowManager.Begin();

            // Create charging session
            var sessionId = _guidGenerator.Create();
            // TransactionId will be auto-generated by database sequence
            // For now, we use a placeholder; the actual transaction ID comes from OCPP/DB
            var session = new ChargingSession(
                sessionId,
                0, // Placeholder - will be set by DB sequence
                chargePointId,
                connectorId,
                idTag,
                meterStart,
                timestamp);

            await _sessionRepository.InsertAsync(session, autoSave: true, cancellationToken: cancellationToken);
            await uow.CompleteAsync();

            _logger.LogInformation(
                "StartTransaction created session {SessionId} with tag {IdTag} on {ChargePointId}, connector {ConnectorId}, meter {MeterStart}Wh",
                sessionId, idTag, chargePointId, connectorId, meterStart);

            // Publish event
            await _eventBus.PublishAsync(new ChargingSessionStartedEto
            {
                SessionId = sessionId,
                TransactionId = session.TransactionId,
                ChargePointId = chargePointId,
                ConnectorId = connectorId,
                IdTag = idTag,
                StartTimestamp = timestamp
            }, cancellationToken: cancellationToken);

            return BuildSuccessResponse(session.TransactionId);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error processing StartTransaction for charge point {ChargePointId}",
                chargePointId);
            return BuildErrorResponse(0, "Invalid");
        }
    }

    private static string ValidateTag(IdTag? tag)
    {
        if (tag == null)
            return "Invalid";

        if (tag.IsBlocked)
            return "Blocked";

        if (tag.IsExpired)
            return "Expired";

        return "Accepted";
    }

    private static JObject BuildSuccessResponse(int transactionId)
    {
        return new JObject
        {
            { "transactionId", transactionId },
            {
                "idTagInfo", new JObject
                {
                    { "status", "Accepted" }
                }
            }
        };
    }

    private static JObject BuildErrorResponse(int transactionId, string status)
    {
        return new JObject
        {
            { "transactionId", transactionId },
            {
                "idTagInfo", new JObject
                {
                    { "status", status }
                }
            }
        };
    }
}
